version: '2.3'

services:

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: vs_server:latest
    container_name: visual_search
    volumes:
      - ./models:/opt/visual_search/models:rw
      - ./images:/opt/visual_search/images:rw
    runtime: nvidia
    ports:
      - 5000:5000
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
    networks:
      - vs_es_net

networks:
  vs_es_net:
    name: vs_es_net
    external: true
